"""init schema

Revision ID: 21703f85991c
Revises: 23551d2c46ef
Create Date: 2025-10-24 19:15:46.527202
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21703f85991c'
down_revision = '23551d2c46ef'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('etiqueta', sa.String(length=100), nullable=False),
    sa.Column('ruta_relativa', sa.String(length=300), nullable=False),
    sa.Column('mimetype', sa.String(length=50), nullable=False),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_etiqueta'), 'documentos', ['etiqueta'], unique=False)
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_nombre'), 'documentos', ['nombre'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'AUDITOR', 'TECNICO', 'EMPRESA', 'MEDICO', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('documento_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('generado_por', sa.String(length=120), nullable=False),
    sa.Column('ruta_relativa', sa.String(length=300), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documento_historial_version'), 'documento_historial', ['version'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('ruc', sa.String(length=32), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('correo_contacto', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_nombre'), 'empresas', ['nombre'], unique=False)
    op.create_index(op.f('ix_empresas_ruc'), 'empresas', ['ruc'], unique=True)
    op.create_table('auditorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('PROGRAMADA', 'EN_PROCESO', 'FINALIZADA', 'CANCELADA', name='estadoauditoria'), nullable=False),
    sa.Column('hallazgos', sa.Text(), nullable=False),
    sa.Column('recomendaciones', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cumplimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('normativa', sa.String(length=120), nullable=False),
    sa.Column('requisito', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.Enum('CUMPLIDO', 'EN_PROCESO', 'NO_CUMPLIDO', name='estadocumplimiento'), nullable=False),
    sa.Column('evidencia', sa.String(length=255), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('severidad', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'CRITICA', name='severidadincidente'), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('acciones_tomadas', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('generado_por', sa.String(length=120), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=255), nullable=False),
    sa.Column('generado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('BASIC', 'PROFESSIONAL', 'ENTERPRISE', name='plansuscripcion'), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'PENDIENTE', 'SUSPENDIDA', 'CANCELADA', name='estadosuscripcion'), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fin', sa.Date(), nullable=False),
    sa.Column('renovacion_automatica', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suscripcion_id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=64), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=5), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'COMPLETADO', 'FALLIDO', name='estadopago'), nullable=False),
    sa.Column('registrado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suscripcion_id'], ['suscripciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referencia')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('suscripciones')
    op.drop_table('reportes')
    op.drop_table('incidentes')
    op.drop_table('cumplimientos')
    op.drop_table('auditorias')
    op.drop_index(op.f('ix_empresas_ruc'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_nombre'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_documento_historial_version'), table_name='documento_historial')
    op.drop_table('documento_historial')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_documentos_nombre'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_etiqueta'), table_name='documentos')
    op.drop_table('documentos')
    # ### end Alembic commands ###
