# Requisitos resumidos de la norma ISO 45001.
requisitos:
  - codigo: ISO-45001-4.1
    descripcion: "Contexto de la organización y necesidades de las partes interesadas."
    periodicidad: anual
  - codigo: ISO-45001-6.1
    descripcion: "Acciones para abordar riesgos y oportunidades en SST."
    periodicidad: semestral
  - codigo: ISO-45001-9.1
    descripcion: "Seguimiento, medición, análisis y evaluación del desempeño."
    periodicidad: trimestral